/**
 * Function to generate a unique numerical string.
 * The string is generated by concatenating the current timestamp and a random 4-digit number.
 * @returns {Promise<string>} The generated unique numerical string.
 */
async function generateNumericalString() {
  const timestamp = Date.now().toString();
  const random = Math.floor(1000 + Math.random() * 9000); // Generate a random 4-digit number

  const uniqueString = timestamp + random.toString();
  return uniqueString;
}

module.exports = generateNumericalString;
