/**
 * Function to generate a unique numerical string.
 * The string is generated by concatenating the current timestamp and a random 4-digit number.
 * @returns {Promise<string>} The generated unique numerical string.
 */
async function generateNumericalString(userRolePrefix) {
  if (typeof userRolePrefix !== String) {
    userRolePrefix.toString();
  }
  const timestamp = Date.now().toString();
  const random = Math.floor(10 + Math.random() * 90); // Generate a random 2-digit number

  const uniqueString =
    userRolePrefix.toLocaleUpperCase() + timestamp + random.toString();
  return uniqueString;
}

module.exports = generateNumericalString;
